# Generated by Django 4.1.11 on 2023-12-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighbour', models.TextField()),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('location', models.TextField()),
                ('neighbours', models.TextField()),
                ('image_urls', models.TextField()),
                ('living_space', models.TextField()),
                ('bedrooms', models.TextField()),
                ('price', models.TextField()),
                ('house_type', models.TextField()),
                ('construction_type', models.TextField()),
                ('construction_year', models.TextField()),
                ('roof_type', models.TextField()),
                ('plot_area', models.TextField()),
                ('contents', models.TextField()),
                ('living_area', models.TextField()),
                ('external_storage_space', models.TextField()),
                ('energy_label', models.TextField()),
                ('insulation', models.TextField()),
                ('heating', models.TextField()),
                ('warm_water', models.TextField()),
                ('cv_ketel', models.TextField()),
                ('Buitenruimte_location', models.TextField()),
                ('garden', models.TextField()),
                ('backyard', models.TextField()),
                ('location_of_garden', models.TextField()),
                ('neighbourhood_facilities', models.TextField()),
                ('price_per_mSq', models.TextField()),
                ('asking_price', models.TextField()),
                ('url', models.TextField()),
                ('price_per_meter_sq_on_plotcore', models.TextField()),
                ('phone_number', models.TextField()),
                ('is_good_property', models.TextField()),
                ('margin', models.TextField()),
            ],
            options={
                'db_table': 'properties',
                'managed': False,
            },
        ),
    ]
