# Generated by Django 4.1.11 on 2024-01-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.TextField()),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
    ]
